### ISSUE TITLE
Error BuildWithDetails on JsonMappingException

### ISSUE THREAD

**Issue by yongwoohan** [jenkinsci/java-client-api#143]
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.offbytwo.jenkins.model.BuildChangeSet out of START_ARRAY token
 at [Source: [B@57175e74; line: 1, column: 1168] (through reference chain: com.offbytwo.jenkins.model.BuildWithDetails["changeSet"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:685)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1215)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2167)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.objectFromResponse(JenkinsHttpClient.java:442)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:149)
	at com.offbytwo.jenkins.model.Build.details(Build.java:43)
	at com.offbytwo.jenckins.test.BuildJobTestReports.main(BuildJobTestReports.java:32)

# _

Before 3 issues same error, I got it
When resolves the issue?

_

**Comment by khmarbaise** [comment]
Can please describe which Jenkins versions you have used and what exactly you have called best would be a code example which results in the above issue...

**Comment by khmarbaise** [comment]
Unfortunately no feedback. And furthermore I can't reproduce this issue with current master state.
