### ISSUE TITLE
IOException no credantials on getJobDetails

### ISSUE THREAD

**Issue by kentilini** [jenkinsci/java-client-api#151]
When trying to get job details, but it throws exception.

I'm using Jenkins with **ssl** and CloudBees **"Folders Plugin"** installed:

Interesting thing that job name with this plugin have such structure:
`%folder_name%/job/%job_name%`

Here simple steps for reproduce:

`JenkinsServer jenkins = new JenkinsServer(new URI(host), "name", "token");`
`JobWithDetails job = jenkins.getJob("job_name");`
`job.details();`

The main problem of such behaviour that 

**Message:**
org.apache.http.HttpException: No credentials for preemptive authentication

**Caused by:**
        org.apache.http.client.ClientProtocolException
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:909)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:141)
    at com.offbytwo.jenkins.model.Job.details(Job.java:40)
    at com.baloise.confluence.dashboardplus.jenkins.JenkinsService.fetchData(JenkinsService.java:43)
    ... 2 more
Caused by: org.apache.http.HttpException: No credentials for preemptive authentication
    at com.offbytwo.jenkins.client.PreemptiveAuth.process(PreemptiveAuth.java:38)
    at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:109)
    at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:176)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:515)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    ... 6 more

**Comment by khmarbaise** [comment]
Which Jenkins version and which version of jenkins-client do you use?

**Comment by kentilini** [comment]
I was tried both 0.3.0 and 0.3.3 versions
Jenkins ver. 1.625.2

**Comment by khmarbaise** [comment]
Can you please recheck with 0.3.5 cause at the moment with current master I can't reproduce this?

**Comment by Bharatj5** [comment]
did you checked given hosted Jenkins URL to JenkinsServer? I was facing same issue due to that.

**Comment by khmarbaise** [comment]
The message `org.apache.http.HttpException: No credentials for preemptive authentication` gives me the impression that the problem is something different.
