### ISSUE TITLE
HttpResponseException: Not Found (createJob)

### ISSUE THREAD

**Issue by GarryBullock** [jenkinsci/java-client-api#176]
Hi there, 

I've been having issues with JenkinsServer.createJob(String jobName, String jobXml). When performing the action I get an http error from the validator (partial stack trace):

`org.apache.http.client.HttpResponseException: Not Found
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:157)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.getQuietly(JenkinsHttpClient.java:203)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:361)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:334)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:298)`

Source of the issue:
![screen shot 2016-08-16 at 3 33 11 pm](https://cloud.githubusercontent.com/assets/14207857/17716631/c8d6725e-63c6-11e6-9480-c86994770d04.png)

The strange thing is the jobs are created.

Jenkins Client API Version: 0.3.5
Jenkins Server Version: 1.642

**Comment by khmarbaise** [comment]
Can you just try using the following method in your code:
``` java
createJob(String jobName, String jobXml, Boolean crumbFlag);
```
like this:
``` java
createJob(job.getjobName(), job.getXML(), false);
```

**Comment by GarryBullock** [comment]
Thanks Karl, adding the false crumbFlag has stopped the error. Just curious as to you know why this stops the error?

**Comment by khmarbaise** [comment]
That's what I assumed, cause there is a bug in the code which calls with crumbFlag=true which is your case wrong...
