### ISSUE TITLE
build.details()  ERROR 

### ISSUE THREAD

**Issue by 278668433** [jenkinsci/java-client-api#177]
when i use  :  
Build build = jobWithDetails.getBuildByNumber(buildNum);
                    if(build != null) {
                        BuildWithDetails buildWithDetails = build.details();
}

ERROR [com.cnc.ciplatform.scheduler.JobTimer] - Can not deserialize instance of com.offbytwo.jenkins.model.BuildChangeSet out of START_ARRAY token
 at [Source: [B@7260050e; line: 1, column: 485](through reference chain: com.offbytwo.jenkins.model.BuildWithDetails["changeSet"])
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of com.offbytwo.jenkins.model.BuildChangeSet out of START_ARRAY token
 at [Source: [B@7260050e; line: 1, column: 485](through reference chain: com.offbytwo.jenkins.model.BuildWithDetails["changeSet"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:685)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1215)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:151)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2167)
    at com.offbytwo.jenkins.client.JenkinsHttpClient.objectFromResponse(JenkinsHttpClient.java:475)
    at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:158)
    at com.offbytwo.jenkins.model.Build.details(Build.java:57)
    at com.cnc.ciplatform.scheduler.JobTimer.monitoringRuningJob(JobTimer.java:88)
    at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by khmarbaise** [comment]
Which version of Jenkins? Which Version of java-client-api ?

**Comment by 278668433** [comment]
Jenkins version  : 1.642.2     &   Version of java-client-api  :    0.3.5

**Comment by khmarbaise** [comment]
Do you have a chance to test with current master of the code? Or should I provide a SNAPSHOT state for testing ?

**Comment by 278668433** [comment]
I solved the problem  by  reWrite the class  BuildChangeSet

		if(changeSetObj instanceof List) {
			List list = (List)changeSetObj;
			Map<String,Object> map = new HashMap<String,Object>();
			map.put("items", list);
			BuildChangeSetMap changeSetMap = new BuildChangeSetMap();
			BeanUtils.populate(changeSetMap, map); 
			System.out.println();
		} else if(changeSetObj instanceof Map) {
			//return a map object
			BuildChangeSetMap changeSetMap = new BuildChangeSetMap();
			BeanUtils.populate(changeSetMap, (Map) changeSetObj); 
			System.out.println();
		}

i will try the problem  when the new version is release

**Comment by khmarbaise** [comment]
Current master works without any issue on Jenkins 2.15 and checked 1.651.3
