### ISSUE TITLE
why Not Found ?when I get the  BuildWithDetails details = jobDetails.getLastBuild().details(); 

### ISSUE THREAD

**Issue by asiainfoJiangmy** [jenkinsci/java-client-api#185]
when I get the details, throw a exception.  
org.apache.http.client.HttpResponseException: Not Found
    at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
    at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:149)

please tell me why ?

**Comment by asiainfoJiangmy** [comment]
I use  0.3.6 version

**Comment by asiainfoJiangmy** [comment]
my  jenkins version is  1.651.3

**Comment by khmarbaise** [comment]
Fixed in 0.3.7
