### ISSUE TITLE
Update job is error

### ISSUE THREAD

**Issue by hanyongwoo** [jenkinsci/java-client-api#195]
org.apache.http.client.HttpResponseException: Server Error
    at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
    at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:370)
    at com.offbytwo.jenkins.JenkinsServer.updateJob(JenkinsServer.java:492)
    at com.offbytwo.jenkins.JenkinsServer.updateJob(JenkinsServer.java:488)
    at com.jtlsoft.ts.build.model.JenkinsControl.updateJobXML(JenkinsControl.java:136)
    at build.test.Main.main(Main.java:18)

**Comment by khmarbaise** [comment]
Can you please share the code you have used to get this error message? Which version of Jenkins do you use?

**Comment by hanyongwoo** [comment]
Jenkins version is latest as a 2.19 and jenkins client version is 0.3.6

JenkinsServer server = new JenkinsServer(new URI("http://localhost:8088/"), "admin", "admin");
server.update(jobName,configXML);

**Comment by khmarbaise** [comment]
Do you have the chance to test with current master code state? I have checked with Jenkins 2.15 and the following code:

``` java
JenkinsServer js = new JenkinsServer( URI.create( "http://localhost:10090/buildserver" ), "admin", "admin" );

String jobXml = js.getJobXml( "test");
js.updateJob( "test", jobXml );
```

This didn't not produce any error...
