### ISSUE TITLE
default api/json?depth=1  cause timeout

### ISSUE THREAD

**Issue by suchasplus** [jenkinsci/java-client-api#220]
due to jenkins api desc:

> Another way to retrieve more data is to use the depth=N query parameter . This retrieves all the data up to the specified depth. Compare depth=0 and depth=1 and see what the difference is for yourself. Also note that data created by a smaller depth value is always a subset of the data created by a bigger depth value.

>Because of the size of the data, the depth parameter should really be only used to explore what data Jenkins can return. Once you identify the data you want to retrieve, you can then come up with the tree parameter to exactly specify the data you need.

in a product env, jenkins always has many jobs/builds. and i always got a 504 Gateway Timeout when retrieve $domain/jenkins/api/json/?depth=1 behind nginx in online jenkins env ( 40+ jobs, 10000+ builds)
Should we disable depth=1 by default ?

**Comment by khmarbaise** [comment]
First how do you call the Java Client API ? Can you show the code you are using? Furthermore which version of Jenkins are you using? and which version of the Java Client API you are using?

**Comment by suchasplus** [comment]
Jenkins ver. 2.19.4
Java-Client-API ver 0.3.7


            jksSrv = new JenkinsServer(new URI(BASE_URL), USER, TOKEN);

            StringBuffer sb = new StringBuffer(4096);

            jksSrv.getViews().forEach((viewName, view) -> {

            sb.append(viewName).append(" ")

                    .append(" url : ")

                    .append(view.getUrl()) ;

           });

I got Gateway timeout

2016-12-30 18:02:11.692 ERROR 33505 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

org.apache.http.client.HttpResponseException: Gateway Time-out
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11) ~[classes/:na]
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:139) ~[classes/:na]
	at com.offbytwo.jenkins.JenkinsServer.getViews(JenkinsServer.java:191) ~[classes/:na]
	at com.offbytwo.jenkins.JenkinsServer.getViews(JenkinsServer.java:179) ~[classes/:na]
	at com.weibo.ad.JenkinsTest.getTest(JenkinsTest.java:46) ~[classes/:na]

**Comment by khmarbaise** [comment]
It looks like the `depth=1` is not necessary and does not makes sense in this relationship.
