### ISSUE TITLE
Cannot run jenkins client

### ISSUE THREAD

**Issue by to-kra** [jenkinsci/java-client-api#227]
Hello,
I this piece of code in my JUnit test
```java
@Test
public void test() throws URISyntaxException, IOException {
	JenkinsServer jenkins = new JenkinsServer(new URI("http://localhost:8080/"), "developer", "123456");
	Map<String, Job> jobs = jenkins.getJobs();
	Assert.assertNotNull(jobs);
}
```

but it fails with this:
![image](https://cloud.githubusercontent.com/assets/2188084/22071429/6a41e766-dd9f-11e6-8cb1-285833284903.png)

I have all dependecies according to maven:
![image](https://cloud.githubusercontent.com/assets/2188084/22071443/7a77d5b4-dd9f-11e6-89b0-bc6ecf1252e0.png)

Do you know what could be the problem ?

**Comment by khmarbaise** [comment]
Which version of Jenkins do you use? Which version of the java-client-api do you use? Can you show the pom file/gradle file etc. you are using ?

**Comment by to-kra** [comment]
@khmarbaise Im using latest jenkins running in docker https://hub.docker.com/_/jenkins/ . But this issue is something in code, because its even before any request is sent. I am using latest pom file which is in **mvn** repository https://mvnrepository.com/artifact/com.offbytwo.jenkins/jenkins-client/0.3.7

**Comment by dmarin** [comment]
I am getting the same error:
`Caused by: java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:494)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:96)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.<init>(JenkinsHttpClient.java:106)
        at com.offbytwo.jenkins.JenkinsServer.<init>(JenkinsServer.java:58)
`

**Comment by khmarbaise** [comment]
First mvnrepository is **NOT** Maven Central. Maven Central is here: https://repo1.maven.org/maven2/. or the search engine for Maven Central is here: https://search.maven.org

Furthermore I have checked with Jenkins 2.32.2 and do not get this exception so in other word it can't be the code...nevertheless can someone please make a whole example project including a pom file which is used which shows the wrong behaviour...so I have a chance to check what's really root cause of this...

Furthermore have some plugins installed in the used docker instance you are using?

**Comment by dmarin** [comment]
in my case it was an issue with gradle and the classpath.

**Comment by khmarbaise** [comment]
can you post the gradle build file and which Gradle version you are using so I can try to find the issue...

**Comment by dmarin** [comment]
i dont think the problem is related to this library. Just moving the depedency to the root build.gradle fixes the issue, i can give you more details if needed but to be honest... your library is good :). The problem is in gradle and how they generate the classpath.

**Comment by khmarbaise** [comment]
Ok Thanks so far.
