### ISSUE TITLE
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')  at [Source: [B@77384bb4; line: 1, column: 2]

### ISSUE THREAD

**Issue by ngnintedemcartelle** [jenkinsci/java-client-api#327]
Please i have this problems when  at this line

JenkinsServer jenkins = new JenkinsServer(new URI(
            "https://signincorp.capgemini.com/opensso/UI/Login?goto=http://s2-training.pl.s2-eu.capgemini.com:80/?permlink=https://s2-training.pl.s2-eu.capgemini.com/jenkins/"),
            "ctidang", "730f2b91da12a592516c062122a46d8c");
        // this is the line wich make this problem
Map<String, Job> jobs = jenkins.getJobs();

        JobWithDetails job = jobs.get("pgw").details();
        System.out.println(job.getName());
        System.out.println(jobs);

**Comment by arthur657834** [comment]
same problem，anyone support？

**Comment by khmarbaise** [comment]
Can someone give more details here...JDK, Jenkins version what was the exact URI which has been used?

**Comment by agoldfain-interview** [comment]
@khmarbaise 
I have the same issue
* java 8
* Jenkins ver. 2.89.4
* jenkins-client 0.3.8

**app**
```
JenkinsServer jenkins = new JenkinsServer(new URI("http://....us/jenkins"), "username", "pword");
System.out.println(jenkins.getJob("job_name"));
```

**error**
```com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@67c27493; line: 7, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1524)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:557)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:475)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2342)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:817)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3031)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2978)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2167)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.objectFromResponse(JenkinsHttpClient.java:514)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:153)
	at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:283)
	at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:270)
	at BuildLog.main(BuildLog.java:14)

Process finished with exit code 0
```
