### ISSUE TITLE
org.apache.http.client.HttpResponseException on disableJob()

### ISSUE THREAD

**Issue by FeiranTao** [jenkinsci/java-client-api#332]
Hi, I am calling disableJob(jobName, true) with my Jenkins instance after logging in with a valid username/token.  I am getting this error even with crumb param set to true. Has anyone been getting this issue?

org.apache.http.client.HttpResponseException: Not Found
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:157)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.getQuietly(JenkinsHttpClient.java:203)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:251)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:438)
	at com.offbytwo.jenkins.JenkinsServer.disableJob(JenkinsServer.java:532)
	at com.salesforce.industries.jenkins.JenkinsConnection.disableJob(JenkinsConnection.java:287)
	at 
Exception in thread "main" org.apache.http.client.HttpResponseException: No valid crumb was included in the request at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:265)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:438)
	at com.offbytwo.jenkins.JenkinsServer.disableJob(JenkinsServer.java:532)

**Comment by khmarbaise** [comment]
Which version of java-client-api are you using? Most recent?

**Comment by FeiranTao** [comment]
it's version 0.3.7

**Comment by kumarshorav11** [comment]
Hey , I am getting this issue using 0.3.8 version of this maven dependency.
I  am able to get the all job from jenkins server and also job details. However, when I am trying to create a new job by using config.xml :
```
<?xml version="1.0" encoding="UTF-8"?>
<project>
	<actions />
	<description>test job from java api</description>
	<keepDependencies>false</keepDependencies>
	<properties />
	<scm class="hudson.scm.NullSCM" />
	<canRoam>true</canRoam>
	<disabled>false</disabled>
	<blockBuildWhenDownstreamBuilding>false
	</blockBuildWhenDownstreamBuilding>
	<blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
	<triggers />
	<concurrentBuild>false</concurrentBuild>
	<builders />
	<publishers />
	<buildWrappers />
	**<crumb>XXX</crumb>
	<crumbRequestField>Jenkins-Crumb</crumbRequestField>**
</project>
```
and then 
```
try {
			jServer.createJob("test-job", "src/main/resources/config.xml",true);
		}catch(Exception e) {
			e.printStackTrace();
		}
```
I am getting below error
Error :
```
org.apache.http.client.HttpResponseException: Forbidden
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:375)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:389)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:359)
	at com.xxx.App.main(App.java:34)
```

**Comment by Little-Little-Bear** [comment]
@khmarbaise ,Hi,  I am using the API to encounter the same problem below. Do you have a chance to find a solution?

Error :

`org.apache.http.client.HttpResponseException: Forbidden
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:262)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post(JenkinsHttpClient.java:434)`
