### ISSUE TITLE
HttpResponseException: Forbidden while trying to call create job in jenkins through java

### ISSUE THREAD

**Issue by kumarshorav11** [jenkinsci/java-client-api#432]
I am using below code to connect to Jenkin server.

```
JenkinsServer jServer = new JenkinsServer(new URI(JENKINS_URL), JENKINS_USER_NAME, JENKINS_PASSWORD);
        Map<String, Job> jobs = jServer.getJobs();

        jobs.forEach((k, v) -> {
            System.out.println("Job ->  " + k.toString());
        });

        JobWithDetails job = jobs.get(JENKINS_JOB_NAME).details();
        job.getBuilds().forEach(b -> System.out.println("Build Details : " + b.getNumber()));
```
I am able to list all the jobs available on the server. However, when I am trying to create a Job by calling .createJob() method by passing job name and config.xml, I am getting the above exception. 
Then, what I did , I changed Jenkin configuration and opted for "Any User can do any thing" option. After this, I am able to create the job. I also observed that When I am giving correct credentials as shown in the above code, java call still logging as anonymous user and hence not able to create a job. 
I also tried using TOKEN to authenticate to jenkins server but no help.
So, how to create job using this api without changing to Jenkin security. It should work within "Logged in user can do any thing" in Jenkin security option.

**Comment by kumarshorav11** [comment]
@tandibar @cosmin Please see this issue. I am not able to connect to the Jenkins Server without modifying the Jenkins-Security as "All Users can do any thing" option in Jenkins configuration. In general, it is logging in to Jenkins as "anonymous" user even though I am passing correct user name and password or username and token with the request. and due to this reason only, I am not able to use job build API to create a job through job.
I donot know how it is logging in to as anonymous user.

**Comment by kumarshorav11** [comment]
some one please verify as I am doing the same thing as described earlier in github page. and I did not found any other way to use this lib on any forum. My Jenkins version is "2.164.3".

**Comment by kumarshorav11** [comment]
```
Exception in thread "main" org.apache.http.client.HttpResponseException: status code: 403, reason phrase: Forbidden
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:375)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:389)
	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:359)
	at com.hcl.OffByTwoJenkins.main(OffByTwoJenkins.java:31)
```
I am getting the above error while creating a job using option "logged in user can do any thing" in Jenkins server settings.
I have below code -
```
HttpClientBuilder builder = HttpClientBuilder.create();
		JenkinsHttpClient client = new JenkinsHttpClient(uri, builder, "XXX", "XXX");
		JenkinsServer jenkins = new JenkinsServer(client);
		String sourceXML = readFile("src/main/resources/config.xml");
		System.out.println(String.format("Installed Jenkins Version >> %s", jenkins.getVersion().getLiteralVersion()));//works and gives correct result
		jenkins.createJob("test-nov1", sourceXML);
```

**Comment by synuwxy** [comment]
> ```
> Exception in thread "main" org.apache.http.client.HttpResponseException: status code: 403, reason phrase: Forbidden
> 	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
> 	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:375)
> 	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:389)
> 	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:359)
> 	at com.xx.OffByTwoJenkins.main(OffByTwoJenkins.java:31)
> ```
> 
> I am getting the above error while creating a job using option "logged in user can do any thing" in Jenkins server settings.
> I have below code -
> 
> ```
> HttpClientBuilder builder = HttpClientBuilder.create();
> 		JenkinsHttpClient client = new JenkinsHttpClient(uri, builder, "XXX", "XXX");
> 		JenkinsServer jenkins = new JenkinsServer(client);
> 		String sourceXML = readFile("src/main/resources/config.xml");
> 		System.out.println(String.format("Installed Jenkins Version >> %s", jenkins.getVersion().getLiteralVersion()));//works and gives correct result
> 		jenkins.createJob("test-nov1", sourceXML);
> ```

You need to turn on the CORS switch in jenkins global security configuration

**Comment by synuwxy** [comment]
@kumarshorav11 
You need to turn on the CORS switch in jenkins global security configuration

**Comment by synuwxy** [comment]
> ```
> Exception in thread "main" org.apache.http.client.HttpResponseException: status code: 403, reason phrase: Forbidden
> 	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
> 	at com.offbytwo.jenkins.client.JenkinsHttpClient.post_xml(JenkinsHttpClient.java:375)
> 	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:389)
> 	at com.offbytwo.jenkins.JenkinsServer.createJob(JenkinsServer.java:359)
> 	at com.xx.OffByTwoJenkins.main(OffByTwoJenkins.java:31)
> ```
> 
> I am getting the above error while creating a job using option "logged in user can do any thing" in Jenkins server settings.
> I have below code -
> 
> ```
> HttpClientBuilder builder = HttpClientBuilder.create();
> 		JenkinsHttpClient client = new JenkinsHttpClient(uri, builder, "XXX", "XXX");
> 		JenkinsServer jenkins = new JenkinsServer(client);
> 		String sourceXML = readFile("src/main/resources/config.xml");
> 		System.out.println(String.format("Installed Jenkins Version >> %s", jenkins.getVersion().getLiteralVersion()));//works and gives correct result
> 		jenkins.createJob("test-nov1", sourceXML);
> ```

You need to turn on the CORS switch in jenkins global security configuration
