### ISSUE TITLE
getComputerSet  error

### ISSUE THREAD

**Issue by LazyJoJo** [jenkinsci/java-client-api#467]
verison:  mvn  0.3.8
code:  List<ComputerWithDetails> list = jenkins.getComputerSet().getComputers();

**Comment by LazyJoJo** [comment]
error:  Exception in thread "main" org.apache.http.client.HttpResponseException: status code: 500, reason phrase: Server Error
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:152)
	at com.offbytwo.jenkins.JenkinsServer.getComputerSet(JenkinsServer.java:556)
